apiVersion: apps/v1
kind: Deployment
metadata:
  name: telimetry-service
  labels:
    app: telimetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telimetry-service
  template:
    metadata:
      labels:
        app: telimetry-service
    spec:
      containers:
      - name: telimetry-service
        image: dts/telemetry
        imagePullPolicy: Never
        env:
        - name: MONGO_DB_ENDPT
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: MONGO_DB_ENDPT
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: RABBITMQ_URL
        - name: INP_QUEUE
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: INP_QUEUE
        - name: OP_QUEUE
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: OP_QUEUE