version: "3"

services:
  app:
    build: .
    # ports:
    #   - "80:5000"
    volumes:
      - ./app:/app
    environment:
      KAFKA_BROKER_ENDPT: kafka
    command: >
      sh -c "python main.py"