apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Confluent-kafka
  region: us-east-1
vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-6391183c }
      us-east-1b: { id: subnet-b0d65ad6 }
nodeGroups:
  - name: Kafka-worker
    labels: { role: workers }
    instanceType: t2.large
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/sandbox_key_vign.pub
    securityGroups:
      attachIDs: ["sg-06fe92df780ca7820"]