apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-tracker
  labels:
    app: delivery-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-tracker
  template:
    metadata:
      labels:
        app: delivery-tracker
    spec:
      containers:
      - name: delivery-tracker
        image: dts/tracker
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_DB_ENDPT
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: MONGO_DB_ENDPT
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: RABBITMQ_URL
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3