apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-simulator
  labels:
    app: delivery-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-simulator
  template:
    metadata:
      labels:
        app: delivery-simulator
    spec:
      containers:
      - name: delivery-simulator
        image: dts/simulator
        imagePullPolicy: Never
        env:
        - name: DATA_PATH
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: DATA_PATH
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: RABBITMQ_URL
        - name: INP_QUEUE
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: INP_QUEUE