apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-tracker
  labels:
    app: delivery-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-tracker
  template:
    metadata:
      labels:
        app: delivery-tracker
    spec:
      containers:
      - name: delivery-tracker
        image: brax2507/delivery-tracker:v1
        readinessProbe: 
          httpGet: 
             path: /
             port: 5000
        env: 
        - name: KAFKA_BROKER_ENDPT
          value: 'kafka'
        - name: MONGO_DB_ENDPT
          value: 'mongo'
        ports: 
        - containerPort: 5000
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties
          secret:
            secretName: kafka-client-config
---
apiVersion: v1
kind: Service
metadata:
   name: delivery-tracker
spec:
   selector:
      app: delivery-tracker
   ports:
      - name: http
        port: 5000
   type: ClusterIP
