apiVersion: apps/v1
kind: Deployment
metadata:
  name: telimetry-service
  labels:
    app: telimetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telimetry-service
  template:
    metadata:
      labels:
        app: telimetry-service
    spec:
      containers:
      - name: telimetry-service
        image: brax2507/telimetry-service:v1
        env: 
        - name: KAFKA_BROKER_ENDPT
          value: 'kafka'
        - name: MONGO_DB_ENDPT
          value: 'mongo'
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties
          secret:
            secretName: kafka-client-config
