apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        imagePullPolicy: Never
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: webapp
spec:
   # this defines which pod is going to be selected for the service
   selector:
   # load balance traffic accross pods based on the selector labels
      app: webapp
   ports:
      - name: http
        port: 80
   type: ClusterIP