apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
  labels:
    app: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: brax2507/bus-1-simulator:latest
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
      volumes:
        - name: kafka-properties
          secret:
            secretName: kafka-client-config