apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-tracker
  labels:
    app: delivery-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-tracker
  template:
    metadata:
      labels:
        app: delivery-tracker
    spec:
      containers:
      - name: delivery-tracker
        image: dts/tracker
        imagePullPolicy: Never
        env:
        - name: MONGO_DB_ENDPT
          value: 'mongodb'
        - name: RABBITMQ_URL
          value: 'rabbitmq'